export const pkgNameList = [
	{pkg: 'com.myfirstapp', name:'잔소리'},
	{pkg: 'com.instagram.android', name:'인스타그램'},
	{pkg: 'com.sec.android.app.clockpackage', name:'시계'},
	{pkg: 'com.sec.android.app.launcher', name:'홈 런처'},
	{pkg: 'com.android.settings', name:'설정'},
	{pkg: 'com.samsung.android.mtp', name:'미디어 전송 프로토콜'},
	{pkg: 'com.moodmemo', name:'MOODMEMO'},
	{pkg: 'com.android.vending', name:'구글플레이스토어'},
	{pkg: 'com.kakao.talk', name:'카카오톡'},
	{pkg: 'com.nhn.android.search', name:'네이버'},
	{pkg: 'com.google.android.youtube', name:'유튜브'},
	{pkg: 'com.google.android.permissioncontroller', name:'권한 컨트롤러'},
	{pkg: 'com.android.settings.intelligence', name:'추천 설정'},
	{pkg: 'com.android.systemui', name:'시스템 UI'},
	{pkg: 'com.android.chrome', name:'크롬'},
	{pkg: 'com.google.android.googlequicksearchbox', name:'구글 검색'},
	{pkg: 'com.samsung.android.app.spage', name:'삼성 스타일 런처'},
	{pkg: 'com.google.android.gm', name:'Gmail'},
	{pkg: 'com.samsung.android.app.galaxyfinder', name:'갤럭시 파인더'},
	{pkg: 'com.wssyncmldm', name:'소프트웨어 업데이트/기기 동기화 서비스'},
	{pkg: 'com.samsung.android.bixby.agent', name:'빅스비 에이전트'},
	{pkg: 'com.example.myapplication', name:'MYAPPLICATION'},
	{pkg: 'com.osp.app.signin', name:'앱 프로필'},
	{pkg: 'com.sec.android.app.camera', name:'카메라'},
	{pkg: 'com.google.android.gms', name:'구글플레이 서비스'},
	{pkg: 'com.sec.android.gallery3d', name:'갤러리'},
]